// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project.Function;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(ProjectContext))]
    [Migration("20240710220516_AddCase")]
    partial class AddCase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Project.Function.Case", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Address_City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address_Line1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address_PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__Case");

                    b.ToTable("Cases", "dbo");
                });

            modelBuilder.Entity("Project.Function.Defendant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Address_City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address_Line1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address_PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__Defendant");

                    b.ToTable("Defendants", "dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
