name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

jobs:
  publish_function_apps:
    runs-on: windows-latest
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:

      - name: Echo Regular Variable (Windows)
        run: |
          echo Repository Owner: %GITHUB_REPOSITORY_OWNER%
          echo Run Number: %GITHUB_RUN_NUMBER%
          echo Run Number: %${{ secrets.PAT_TOKEN }}%
        shell: cmd

      - name: Authenticate with GitHub Packages
        run: |
          dotnet nuget remove source GitHubPackages || true
          dotnet nuget add source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
            --name GitHubPackages \
            --username ${{ github.repository_owner }} \
            --password ${{ secrets.PAT_TOKEN }} \
            --store-password-in-clear-text

      - name: Restore dependencies
        run: dotnet restore --configfile nuget.config --no-cache --force